### ISSUE TITLE
initial documentation

### ISSUE THREAD

**Issue by danielroe** [nuxt/fonts#6]
```[tasklist]
### Tasks
- [x] basic information here on usage and how the module works
- [x] example of how to write a custom provider (+ register one in a module)
- [x] more examples on customisation and advanced usage
```
